//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenShare.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenShare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AVIファイル(*.avi)|*.avi に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AVIFilter {
            get {
                return ResourceManager.GetString("AVIFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptureError {
            get {
                return ResourceManager.GetString("CaptureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャ失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptureFailed {
            get {
                return ResourceManager.GetString("CaptureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャ開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptureStarted {
            get {
                return ResourceManager.GetString("CaptureStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャ開始中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptureStarting {
            get {
                return ResourceManager.GetString("CaptureStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャ終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptureStopped {
            get {
                return ResourceManager.GetString("CaptureStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャプチャ終了中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CaptureStopping {
            get {
                return ResourceManager.GetString("CaptureStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロセスが存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessNotFound {
            get {
                return ResourceManager.GetString("ProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   録画キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecordCancelled {
            get {
                return ResourceManager.GetString("RecordCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   録画失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecordFailed {
            get {
                return ResourceManager.GetString("RecordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   録画開始中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RecordStarting {
            get {
                return ResourceManager.GetString("RecordStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   サーバ切断完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerClosed {
            get {
                return ResourceManager.GetString("ServerClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバ切断中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerClosing {
            get {
                return ResourceManager.GetString("ServerClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバ設立失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerFailed {
            get {
                return ResourceManager.GetString("ServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバ設立完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerStarted {
            get {
                return ResourceManager.GetString("ServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバ設立中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerStarting {
            get {
                return ResourceManager.GetString("ServerStarting", resourceCulture);
            }
        }
    }
}
